### ISSUE TITLE
一些代码中的问题

### ISSUE THREAD

**Issue by hpompom** [YifanJiang233/Deep_BSDE_solver#1]
您好，在E, W.; Han, J.; Jentzen（2017）中，算法应为在每个时点用于计算z的神经网络是不同的并且需要同时估计，但是您的网络好像是所有时点的神经网络为同一个。
<img width="635" alt="image" src="https://user-images.githubusercontent.com/50010628/135264247-ce6ab96a-b600-4ebe-acfe-d85d58e38bf7.png">

**Comment by YifanJiang233** [comment]
您说的完全正确，我们的算法将时间也作为了网络的输入，从而只需要一个网络。我们认为将时间和状态一同输入是对解耦场 $u$ 更自然的刻画。从数值计算角度出发，随着时间节点增多，只使用一个网络在计算资源消耗上也更少。

**Comment by hpompom** [comment]
谢谢您的解答！还有一个问题，这样子做会不会导致最后结果计算精度下降？我们或许要在计算精度和计算资源上做出一个平衡

**Comment by YifanJiang233** [comment]
在这个例子中，两种网络的精度是差不多的。文章主要关心的是通过后验估计给出数值解的误差上界，但不同结构的神经网络究竟能把误差上界减少到多少不在文章研究的范围内。计算精度还是依赖于问题本身和神经网络的结构，很难说有一种网络结构对所有方程都有更高的精度。

**Comment by hpompom** [comment]
谢谢您的解答！祝一切顺利！
